# Academic Services
- role: "Conference Reviewer"
  detail: "AAAI 2026"

- role: "Journal Reviewer"
  detail: "IEEE Internet of Things Journal (IoT-J), since 2026"
- role: "Journal Reviewer"
  detail: "IEEE Sensors Journal, since 2026"
